### ISSUE TITLE
Monroe results "crash" bc pangolin output columns changed

### ISSUE THREAD

**Issue by kittychaseNC** [StaPH-B/staphb_toolkit#56]
#create output file
  with open(f"monroe_summary_{today}.csv",'w') as csvout:
      writer = csv.writer(csvout,delimiter=',')
      writer.writerow(["sample","aligned_bases","percent_cvg", "mean_depth", "mean_base_q", "mean_map_q", "monroe_qc", "pangolin_lineage", "pangolin_probability", "pangolin_notes"])
      for id in results:
          result = results[id]
          writer.writerow([result.id,result.aligned_bases,result.percent_cvg,result.mean_depth,result.mean_base_q,result.mean_map_q,result.monroe_qc,result.pangolin_lineage,result.pangolin_probability,result.pangolin_notes])

Command exit status:
  1

Command output:
  (empty)

 Pangolin probability no longer exists

**Comment by kevinlibuit** [comment]
Thanks for raising this issue, @kittychaseNC! I've seen this output update crash a few SC2 workflows and now we can add Monroe to the list. The fix is relatively straight forward: you should only need to grab the "conflict" columns rather than the old "probability" outputs in [places like this](https://github.com/StaPH-B/staphb_toolkit/blob/master/staphb_toolkit/workflows/monroe/monroe_pe_assembly.nf#L237) for every workflow that leans on pangolin. Either that or scrap the probability/conflict scores from the final report all together; this information would still be accessible within the pangolin lineage report, just not floated to the final monore report itself. 

Unfortunately, I likely won't have time to work out which route is best for the workflow, make the change and then validate functionality until (at best) the end of the week. If you have a bit more bandwidth on your end and need this fix more urgently, please feel free to submit a PR from your end and I would be more than happy help validate things before merging.

Tagging @k-florek and @AbigailShockey as the Monroe ONT workflows are also impacted here.

**Comment by k-florek** [comment]
@kevinlibuit I might be able to address this today or tomorrow. I can change the probability column to reflect the conflict result.

**Comment by k-florek** [comment]
@kevinlibuit @kittychaseNC I just pushed an update that fixed the issue. Please let me know if you find any issues or additional problems.
